### PR TITLE
[Fix]: Issue 27 - Back button from Settings

### PR DESCRIPTION
**Pull request by JarrydTrokis**
#### This PR adds the ability to go back to the `wallet` screen from the settings `screen`

Link to issue: https://github.com/OLSF/carpe/issues/27

At present, this is simply a conditional check based on the current route pathname (see more info below). If the user is on the settings screen, the button will be displayed in the Nav.

image

## Additional Change
I've taken the liberty of adding a `routes.ts` file to ensure that we have consistent routing across the application. The "magic string" approach we were using before is error-prone. This change has better auto-complete and keeps our code re-usable. 👌 

##### Further info
When developing locally, there is no mechanism for a redirect serving the application. Which means that when on a route other than `/` the application doesn't load. This will need to be resolved in a future fix version and is not a priority; given that it only affects DX at this stage.

### CODE REVIEW

**Comment by JarrydTrokis** [comment]
@soaresa @mortonbits Ready for your review 🙏

**Review by mortonbits — APPROVED** [review]

**Comment by mortonbits** [comment]
Love it. Would be great to have this back button also on the "restere account" or "new account" page.

**Comment by JarrydTrokis** [comment]
@mortonbits I can submit a follow-up PR once this is merged in 👍  I have some UX/UI ideas that I want to submit ... so am working on those

**Comment by soaresa** [comment]
Hi @JarrydTrokis , please solve the conflicts before I can merge it. Thanks!

**Comment by soaresa** [comment]
> @mortonbits I can submit a follow-up PR once this is merged in +1 I have some UX/UI ideas that I want to submit ... so am working on those

@JarrydTrokis , please let me know what you are up to with UI/UX ideas so we can put it on the roadmap and avoid duplicated work. Thanks!

**Pull request merged**
