### PR TITLE
[wallet] show wallet type

### PR DESCRIPTION
**Pull request by ea-open-source**
## Motivation

**This PR adds the ability to show the current wallet type**

Link to mission: [Carpe: Display Wallet type](https://airtable.com/shrCuXWvrZgHkspk7/tblixhNzkEaKt3a75/viwlz7S2kmgCkoHFS/recb40uttTa5heQlh)

## Related PRs

[[cli] API for getting wallet type #994](https://github.com/OLSF/libra/pull/994)

___

image

### CODE REVIEW

**Comment by 0o-de-lally** [comment]
Thank you this is a good contribution. My preference is to have it as a field or an icon in the AccountList table in Wallet view. Can we try that?

**Comment by soaresa** [comment]
Nice work @ea-open-source ! Could you please initialize the account type with "Normal" on the Rust side? It is better to avoid front-end code to decide if type is null than shows "Normal". Thanks!

**Comment by ea-open-source** [comment]
> Nice work @ea-open-source ! Could you please initialize the account type with "Normal" on the Rust side? It is better to avoid front-end code to decide if type is null than shows "Normal". Thanks!

Hi @soaresa, thanks for your review.
Since we were not the originator of the account type system on the Rust side what we have done here's just an extension of it.
Correct me if I'm wrong but you want us to default account initilization with Normal type and show that on Carpe without any FE type-checking shenanigans?

**Comment by jayhxmo** [comment]
@0o-de-lally Curious - why is your preference to be an icon? While a table view looks a little boring, I find that icons by themselves can be confusing to first-time users. Are there any usages / displaying of wallet types that are used in places other than this view?

**Comment by soaresa** [comment]
> > Nice work @ea-open-source ! Could you please initialize the account type with "Normal" on the Rust side? It is better to avoid front-end code to decide if type is null than shows "Normal". Thanks!
> 
> Hi @soaresa, thanks for your review. Since we were not the originator of the account type system on the Rust side what we have done here's just an extension of it. Correct me if I'm wrong but you want us to default account initilization with Normal type and show that on Carpe without any FE type-checking shenanigans?

What I mean is it would be better to return the type "Normal" in your new tauri command ```query_wallet_type``` avoiding the ```if``` statement in the svelte component: 

```
{#if a.wallet_type === "None"}
  Normal
{:else}
  {a.wallet_type}
{/if}
```

We will display the account type in new svelte components soon and we should avoid calculate the "Normal" type on them.

**Pull request merged**
