### PR TITLE
Initial carpe start: Read list of full nodes from repo

### PR DESCRIPTION
**Pull request by mortonbits**
Related to Issue https://github.com/OLSF/carpe/issues/33

Content of this pull request:
- 6 full nodes are listed in a json file in public/fullnodes.json
- seed_peers.rs reads this list. If content not found or cannot be parsed, fallback to 3 configured nodes in source code

This code is currently only visited on initial startup of carpe (or if 0L.toml is deleted).

Potential enhancement which can use this PR as base: Issue https://github.com/OLSF/carpe/issues/29

### CODE REVIEW

**Review by soaresa — APPROVED** [review]
Looks nice! Thanks for adding the timeout when checking peer.

We are in a much better peer connection condition with this PR. 

Looking forward to have a lazy check for the random selected peer. I will open an issue for it, but we are good to go with this PR.

**Review by soaresa — APPROVED** [review]
Thanks!

**Comment by liangping** [comment]
@mortonbits https://raw.githubusercontent.com/OLSF/carpe/main/public/fullnodes.json
this domain is banned in China. wonder if you could add exception handler.

**Comment by liangping** [comment]
@mortonbits https://raw.githubusercontent.com/OLSF/carpe/main/public/fullnodes.json
this domain is banned in China. wonder if you add exception handler.

**Comment by mortonbits** [comment]
@liangping - to be safe, I added a timeout when requesting https://raw.githubusercontent.com/OLSF/carpe/main/public/fullnodes.json

**Review by soaresa — APPROVED** [review]
Looks good!

**Pull request merged**
